stages:
  - test
  - build

image: tdba/simapi:sbcl_2.1.9


before_script:
  - git clone https://github.com/jeosol/hello-world.git ~/quicklisp/local-projects/

test:
 stage: test
 script:
   - make test

build:
 stage: build
 only:
   - tags
 script:
   - make build
 artifacts:
 paths:
   - 
          
 script:
   - echo 'Hello World'
